import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  contenedor: { flex: 1, backgroundColor: "#ececec" },
  navbar: {
    backgroundColor: "#ffffff",
    paddingTop: 60,
    paddingBottom: 20,
    paddingHorizontal: 20,
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#d1d1d1",
    elevation: 2,
  },
  bloqueTitulos: { alignItems: "center", marginBottom: 15 },
  headerTitulo: { fontSize: 24, fontWeight: "900", color: "#2f5279" },
  headerSubtitulo: { fontSize: 16, fontWeight: "600", color: "#e67e22" },
  contenedorDificultad: {
    flexDirection: "row",
    backgroundColor: "#f0f0f0",
    borderRadius: 12,
    padding: 4,
    width: "100%",
    marginBottom: 15,
  },
  opcionDificultad: { flex: 1, paddingVertical: 10, alignItems: "center", borderRadius: 8 },
  opcionSeleccionada: { backgroundColor: "#2f5279" },
  textoOpcion: { color: "#7f8c8d", fontWeight: "700" },
  textoSeleccionado: { color: "#ffffff" },
  contenedorTiempo: {
    backgroundColor: "#fdf2e9",
    paddingHorizontal: 15,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e67e22",
  },
  textoTiempo: { color: "#e67e22", fontWeight: "800" },
  cuerpo: { flex: 1, padding: 15, justifyContent: "center" },
  
  // UNIFICADO: Sin duplicados para evitar error ts(1117)
  espacioJuego: {
    minHeight: 320,
    backgroundColor: "#ffffff",
    borderRadius: 25,
    borderWidth: 1,
    borderColor: "#bdc3c7",
    borderStyle: "dashed",
    padding: 15,
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textoResumen: { fontSize: 16, color: "#2f5279", marginBottom: 15, fontWeight: '700' },
  cuadrillaCartas: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartaMiniatura: {
    width: 46,
    height: 62,
    backgroundColor: "#fcfcfc",
    borderRadius: 8,
    margin: 3,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
    borderWidth: 1,
    borderColor: '#eee',
  },
  emojiCarta: { fontSize: 24 },
  botonIniciar: {
    backgroundColor: "#2f5279",
    paddingVertical: 16,
    paddingHorizontal: 60,
    borderRadius: 30,
    alignSelf: "center",
  },
  textoBoton: { color: "#ffffff", fontSize: 18, fontWeight: "bold" },
});